Repository fivejars/openy, pull requests merged in 2020-08, with the labels that each got.

#87 [CR-5]: Embedded images and videos
  modules/custom/openy_ckeditor/css/openy_ckeditor.admin.css
  modules/custom/openy_ckeditor/openy_ckeditor.module
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/main.js
  themes/openy_themes/openy_carnation/src/scss/_base.scss
  themes/openy_themes/openy_carnation/src/scss/component/_embedded_content.scss
Labels: REVIEWED, TESTED

#90 [CR-10]: Carnation: Fix gallery view, blazy, add thumbnails and prev/…
  composer.json
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/config/install/image.style.gallery_thumbnail.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/js/openy_prgf_gallery.carnation.js
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.install
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.libraries.yml
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_gallery.scss
  themes/openy_themes/openy_carnation/src/scss/presentation/_variables.scss
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--gallery--default.html.twig
Labels: REVIEWED, TESTED

#92 [CR-12][CR-13]: Fixes for location teasers
  modules/custom/openy_data_wrapper/src/DataWrapper.php
  openy.info.yml
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_locations.scss
  themes/openy_themes/openy_carnation/templates/node/node--location-type--teaser.html.twig
Labels: NEEDS REVIEW, REVIEWED, TESTED

#93 [CR-12]: Open Directions link in a new tab
  modules/openy_features/openy_location/modules/openy_loc_branch/config/install/core.entity_view_display.node.branch.teaser.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.install
  modules/openy_features/openy_location/modules/openy_loc_camp/config/install/core.entity_view_display.node.camp.teaser.yml
  modules/openy_features/openy_location/modules/openy_loc_facility/config/install/core.entity_view_display.node.facility.teaser.yml
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/templates/field/field--field-location-directions--teaser.html.twig
  themes/openy_themes/openy_carnation/templates/node/camp/node--camp--teaser.html.twig
  themes/openy_themes/openy_carnation/templates/node/node--location-type--teaser.html.twig
Labels: REVIEWED, TESTED

#95 [CR-14] Microsite menu current page link highlight
  modules/openy_features/openy_block/modules/openy_block_menu/openy_block_menu.install
  modules/openy_features/openy_block/modules/openy_block_menu/openy_block_menu.module
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_microsites.scss
Labels: REVIEWED, TESTED

#89 [CR-7][CR-8]: Main menu and user page fixes
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/src/scss/modules/_menu.scss
Labels: NEEDS REVIEW, NEEDS TESTING

#96 [CR-15] Fix location finder spacing
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_location.scss
  themes/openy_themes/openy_carnation/templates/views/views-view-unformatted--locations.html.twig
Labels: REVIEWED, TESTED

#97 [CR-16] Align Google Translate widget with the other menu items
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_gtranslate.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_header.scss
Labels: REVIEWED, TESTED

#105 Carnation refactoring
  composer.json
  modules/custom/openy_activity_finder/src/Plugin/Block/ActivityFinderBlock.php
  modules/custom/openy_activity_finder/src/Plugin/Block/CampFinderBlock.php
  modules/custom/openy_search/openy_google_search/openy_google_search.services.yml
  modules/custom/openy_search/openy_google_search/src/OpenyGoogleSearchHelperService.php
  modules/custom/openy_search/openy_search_api/openy_search_api.module
  modules/openy_features/openy_demo_content/modules/openy_demo_bfooter/config/install/migrate_plus.migration.openy_demo_block_content_footer.yml
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
  openy.info.yml
  themes/openy_themes/openy_carnation/templates/field/field--link.html.twig
  themes/openy_themes/openy_carnation/templates/field/field--paragraph--field-prgf-link--gallery.html.twig
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_landing.scss
Labels: NEEDS REVIEW

#104 [CR-27] Home branch sorting fix
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/js/hb-location-finder-override.js
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/src/scss/modules/_location.scss
  themes/openy_themes/openy_carnation/templates/views/views-view-unformatted--locations.html.twig
Labels: REVIEWED, TESTED

#106 Sync upstream
  composer.lock
  modules/custom/openy_field_faq/openy_field_faq.module
  modules/custom/openy_field_faq/src/Plugin/Field/FieldFormatter/FaqDefault.php
  modules/custom/openy_field_faq/templates/openy-faq-item.html.twig
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/js/paragraph.js
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/_base.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_faq.scss
  themes/openy_themes/openy_carnation/templates/modules/openy-faq-item.html.twig
Labels: NEEDS REVIEW

#114 Sync carnation-refactoring branch with fivejars and upstream
  composer.json
  composer.lock
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/SelectionNoDependencyTrait.php
  modules/custom/openy_field_faq/openy_field_faq.module
  modules/custom/openy_field_faq/src/Plugin/Field/FieldFormatter/FaqDefault.php
  modules/custom/openy_field_faq/templates/openy-faq-item.html.twig
  modules/custom/openy_group_schedules/openy_group_schedules.module
  modules/custom/openy_group_schedules/src/Form/GroupexFormFull.php
  modules/custom/openy_group_schedules/src/Form/GroupexFormLocation.php
  modules/custom/openy_group_schedules/src/GroupexScheduleFetcher.php
  modules/custom/openy_redirect/openy_redirect.module
  modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--sidebar.html.twig
  modules/custom/openy_upgrade_tool/src/Controller/OpenyUpgradeLogController.php
  modules/openy_features/openy_node/modules/openy_node_event/js/openy_node_event.js
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/js/paragraph.js
  modules/openy_features/openy_taxonomy/src/Plugin/views/filter/BetterTaxonomyIndexTid.php
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/js/hb-location-finder-override.js
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/src/scss/_base.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_faq.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_location.scss
  themes/openy_themes/openy_carnation/templates/modules/openy-faq-item.html.twig
  themes/openy_themes/openy_carnation/templates/node/event/node--event--full.html.twig
  themes/openy_themes/openy_carnation/templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig
  themes/openy_themes/openy_carnation/templates/views/views-view-unformatted--locations.html.twig
Labels: NEEDS REVIEW
